# install_roles.yml

# from galaxy
- src: geerlingguy.nodejs
  version: 3.3.1
  name: nodejs

- src: geerlingguy.git
  version: 1.2.1
  name: git

- src: nickp666.android-sdk
  version: v0.0.7
  name: android-sdk