---
- hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  vars:
    # nodejs role vars
    nodejs_npm_global_packages:
    - name: cordova
    - name: monaca
  roles:
    - git
    - { role: "nodejs", nodejs_version: '6.x'}
    - { role: "android-sdk" }
